name: Deploy Production

on:
  workflow_dispatch:
      inputs:
        Changes:
          description: 'New Deployment Production'     
          required: true
          default: 'changes'

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: aws s3 sync --exclude ".github/*" --exclude ".git/*" --exclude "README.md" ./ 's3://webflow-xt/knockout/'
      - run: aws s3 sync --exclude ".github/*" --exclude ".git/*" --exclude "README.md" ./ 's3://webflow-xt/knockout/' --delete
